export enum Region {
  TUNIS = 'TUNIS',
  BEN_AROUS = 'BEN_AROUS',
  ARIANA = 'ARIANA',
  MANOUBA = 'MANOUBA',
  NABEUL = 'NABEUL',
  ZAGHOUAN = 'ZAGHOUAN',
  BIZERTE = 'BIZERTE',
  BEJA = 'BEJA',
  JENDOUBA = 'JENDOUBA',
  KEF = 'KEF',
  SILIANA = 'SILIANA',
  SOUSSE = 'SOUSSE',
  MONASTIR = 'MONASTIR',
  MAHDIA = 'MAHDIA',
  SFAX = 'SFAX',
  KAIROUAN = 'KAIROUAN',
  KASSERINE = 'KASSERINE',
  SIDI_BOUZID = 'SIDI_BOUZID',
  GABES = 'GABES',
  MEDENINE = 'MEDENINE',
  TATAOUINE = 'TATAOUINE',
  GAFSA = 'GAFSA',
  TOZEUR = 'TOZEUR',
  KEBILI = 'KEBILI'
}



